<a href="#" id="back-to-top" title="Back to top">
  <i class="fa fa-angle-up"></i>
</a>

<!-- BEGIN GOOGLE ANALYTICS CODE -->
<script type="text/javascript">
  var GoogleTrackAccount = 'UA-0000000-0';
</script>

<script src="../../../../vlInclude/ga-universal.js"></script>
<!-- #include file="../../../../Content/ASP/TransactionAnalytics_Universal_NetCart.asp" -->
<!-- END GOOGLE ANALYTICS CODE -->

<form name="LogoutForm" id="LogoutForm" method="post">
  <input type="hidden" id="Logoff" name="Logoff" value="Logoff">
</form>

<div class="modal fade" id="bootLogin" tabindex="-1" role="dialog" aria-labelledby="bootLogin" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAVCAYAAABCIB6VAAAB/UlEQVRIS62VPWxNYRzGfw9CYiBhoAuLj8kijUlM3NZXaGgRQ2tRGhGJWAmrYJBI08VHQggh0iZtMYmNWEzSiYWFRAcJKY/8m/+96ri9p7ftu51z3vN7n/O8z/scAdg+BTyS9DmuZztsrwY6JV2X7V6gHxgDdkj6MBuw7bXAc2A90BvglcAzYDPwEdguKRaZ8bC9IaFrgLdARWnFcmAI2AqEHRVJ72ZCtr0phYUNr4A9kr5NghO+FHgaioEvQLukN43gtluBUWBFKt4v6Xu8UwMnfAnwANgHjAN7Jb2sB7e9DRgElqWgQ5J+VOf+A074IuAOcASI1TskxR7Uhu024DEQX3kP6JY0MXXOf+CELwRuAMeBn8BhSU/yWQdwH1gMDAB9kn4Vv6ouOAHx7CpwBgg1PfnybSAWvgacleR6Vk0LnrKpF4HzwO+8twC4JOlCo40tBaf64UhJgoYl7SqLYinY9vwqth2LXg4fgdicY6nyZnp8BTjXlMe2m0nFSUlV/2sOTZfjW8DRzPEBSSOFHO+MNswc343ENMyx7bmcvC5JkfnJUeyKOAQV4Gt2xeuSrtgCRGKiK+J0xin92xW259pu0cOrst12Sxqv9nF4GE0VfRyV+b4spwXPN6bi6ONoxPb5/oO8ANYBJ6pFfxp4KOlTM0qLc223AAfjn/cH0w3V/eQPeBgAAAAASUVORK5CYII=">
                </button>
            </div>
            <div class="modal-body">
                <iframe></iframe>
            </div>
        </div>
    </div>
</div>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/selectivizr/1.0.2/selectivizr-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
<![endif]-->

<script type="text/javascript" src="/dsn/"<%=ChildDSN%>/Content/Javascripts/site-functions.js">
</script>


